[server]
log_file = "openttd_server.log"

[ai]
enable = true
ignore_client = "ChatBotAI"
model = "OTTD-Chatbot"
system_prompt = "Never use any emoji in your response! You are the host and observer of an OpenTTD server. Be funny and short. You can use muti line"
